name: Build Web WASM and Publish Page

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Run tests
        run: cargo test

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build Web WASM
        run: wasm-pack build wasm --target web --out-dir ../web/pkg

      - name: Upload to GH Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: web

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GH Pages
        uses: actions/deploy-pages@v4
